### ISSUE TITLE
Docs request: installing container as service

### ISSUE THREAD

**Issue by SamuelMarks** [cloudfoundry-community/cf-containers-broker#41]
Been scratching my head a little. Okay, so I have:

  1. [Bosh lite](https://github.com/cloudfoundry/bosh-lite) ([vagrant](https://www.vagrantup.com) with [virtualbox](https://www.virtualbox.org))
  2. [Cloudfoundry](https://github.com/cloudfoundry/cf-release) (provisioned on ^)
  3. [cf-containers-broker](https://github.com/cloudfoundry-community/cf-containers-broker) (installed on ^; as per [your README.md](https://github.com/cloudfoundry-community/cf-containers-broker/blob/ec27285d4518af23a46b416848b443e1fecfb121/README.md))

Now scrolling down to [DOCKER.md#example](https://github.com/cloudfoundry-community/cf-containers-broker/blob/2e68391c3a7a20798d1116bda9cabfd7d0528a12/DOCKER.md#example) where there's a little bit of [YAML](http://www.yaml.org) specifying a [Docker](https://www.docker.com) [image](https://docs.docker.com/engine/userguide/dockerimages) &etc.

Okay, what's the next step? - Say I want to **use** that [YAML](http://www.yaml.org); to pull a [Docker image](https://docs.docker.com/engine/userguide/dockerimages), run the [container](https://docs.docker.com/engine/userguide/dockerizing) inside [cloudfoundry](https://github.com/cloudfoundry/cf-release), and register it as a [cloudfoundry service](https://docs.cloudfoundry.org/devguide/services)… how?

**Comment by vlerenc** [comment]
The main purpose (at least in my eyes) of this broker is to use it in combination with https://github.com/cloudfoundry-community/docker-boshrelease either in a single-node Docker or a multi-node Docker - Swarm setup. The broker (catalog) will advertise the Docker images as service/plans (defined in the deployment manifest) and when users instantiate services/create service instances, the broker will spin up containers with that image.

I am not sure what you try to achieve, but the broker won't be able to speak to CF - it implements the native Docker interface (when calling out) and the service broker interface (for being called by the CF cloud controller).

So, it cannot spin up a container in CF (as CF doesn't speak the Docker ReST API). On the other hand, if you run a container yourself (or any general service app for that matter), you can create a user provided service manually.

**Comment by Amit-PivotalLabs** [comment]
If you have docker running, `cf-containers-broker` running in docker, and the broker registered with CF (running in BOSH-Lite), how then could you start a mongoDB docker container and use that as a bound service for an application in CF?

What are the steps to actually use [this example](https://github.com/cloudfoundry-community/cf-containers-broker/blob/2e68391c3a7a20798d1116bda9cabfd7d0528a12/DOCKER.md#example)? The YAML is given there without much context, not clear what you actually do with it.

**Comment by SamuelMarks** [comment]
@vlerenc *bump*, interested in @Amit-PivotalLabs question also.

Thanks

**Comment by vlerenc** [comment]
Well, as said, the idea is to use everything together in https://github.com/cloudfoundry-community/docker-boshrelease (you don't have to install/operate the individual bits). In such a scenario, the answer to the question above is: register the broker at CF/the cloud controller (either with the given errand or manually with the CF CLI) and then you can use the Docker based services as any other hosted service. In other words, the services will appear in the marketplace (after enabling them with cf enable-service), you can create-service, delete-service, bind-service, unbind-service them.

**Comment by SamuelMarks** [comment]
Thanks, looking forward to this issue being resolved so I can try that:
https://github.com/cloudfoundry-community/docker-boshrelease/issues/47
