### ISSUE TITLE
Overriding credentials - hostname

### ISSUE THREAD

**Issue by yatzek** [cloudfoundry-community/cf-containers-broker#44]
Currently host returned in service credentials is an ip address of of the machine running the broker.
I would like to be able to specify a hostname that is returned instead. 

Example:  

credentials:
  username:
    key: 'SERVICE_USERNAME'
    value: 'admin'
  password:
    key: 'SERVICE_PASSWORD'
  dbname:
    key: 'SERVICE_DBNAME'
  hostname:
    key: 'SERVICE_HOSTNAME'
    value: 'postgres-01.docker.com'
  uri:
    prefix: 'mongodb'
    port: '27017/tcp'

**Comment by vlerenc** [comment]
The address is the one of the container host respectively whatever you have configured there.
