### ISSUE TITLE
Support other URI patterns

### ISSUE THREAD

**Issue by s-bortolussi** [cloudfoundry-community/cf-containers-broker#70]
When an application is bound to the service, it will receive a credentials hash with an URI following this pattern: ``mongodb://admin:<RANDOM PASSWORD>@<HOST IP>:<HOST PORT MAPPED TO CONTAINER PORT 27017/tcp>/<RANDOM DBNAME>``.

Some database uris, such as [influxdb](https://github.com/influxdata/influxdb), don't follow this pattern. Uris are then  defined without database specificed as uri path ( ex : ``http://admin:<RANDOM PASSWORD>@<HOST>:<PORT>`` )

Just wondering if such a pattern could be supported  ?

Thanks

**Comment by drnic** [comment]
Can you give `prefix: http` a try?

**Comment by s-bortolussi** [comment]
Hi @drnic, 

Thanks for your quick response. 
Specifying http as a scheme gives me following uri : `http://admin:password@host:port/dbname`` whereas influxdb requires ``http://admin:password@host:port``

**Comment by drnic** [comment]
https://github.com/cloudfoundry-community/cf-containers-broker/blob/master/app/models/credentials.rb#L97

You should only get the suffix dbname if you've included it in your service plan.

**Comment by s-bortolussi** [comment]
Thanks for your help @drnic.

Indeed, on service binding I would need to get something credentials like this :
```
"credentials": {
     "dbname": "dsrm0paktgy63qzl",
      "uri": "http://<user>:<password>@<host>:<port>",
	 ...
    },
```

where 
- dbname is still set by the service broker
- uri does not contain any dbname value

**Comment by drnic** [comment]
Awesome
